---
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    hostname: app.lead.local
    networks:
      default:
        aliases: ["app"]
    ports:
      - "127.0.0.1:2300:2300"
    depends_on:
      mariadb:
        condition: "service_healthy"
    volumes:
      - .:/lead
    command: ["sleep", "infinity"]

  app-dev:
    profiles: [ "test" ]
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    depends_on:
      mariadb:
        condition: "service_healthy"
    volumes:
      - .:/lead
    command: ["sleep", "infinity"]

  mariadb:
    image: bitnami/mariadb
    hostname: db.lead.local
    networks:
      default:
        aliases: ["db"]
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mariadb_data:/bitnami/mariadb
      - ./db:/sql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=lead
      - MARIADB_USER=lead
      - MARIADB_PASSWORD=lead
      - TZ=America/Detroit
    healthcheck:
      test: ["CMD", "mariadb-admin", "-u", "root", "status"]
      interval: "10s"
      timeout: "10s"
      retries: 3

volumes:
  mariadb_data:

networks:
  default:
