---
# A placeholder for branch workflow development
# (so you can create and debug workflows on a branch other then main).
name: Scratch

on:
  workflow_dispatch:
    inputs:
      tag:
        default: 'latest-default-tag'
        description: tag
        required: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: create .env
        run: |
          echo "UID=$(id -u)" > .env
          echo "GID=$(id -g)" >> .env
      - name: save short tag to environment
        run: echo "short_tag=$(echo ${{ github.event.inputs.tag }} | head -c 8 )" >> $GITHUB_ENV
      - name: echo env var
        run: echo "${{ env.short_tag }}"
      - name: arch
        run: ARCH=$(arch | sed s/aarch64/arm64/ | sed s/x86_64/amd64/); echo $ARCH
      - name: env
        run: env
